### ISSUE TITLE
Adopt pre-commit hooks

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/safedata#12]
See here:

https://github.com/lorenzwalthert/precommit

**Comment by davidorme** [comment]
I'm having issues installing the hooks - could be a temporary network thing?

Error log content below
<details>
### version information

```
pre-commit version: 3.3.2
git --version: git version 2.30.0
sys.version:
    3.10.4 (main, Jun 27 2022, 15:55:10) [Clang 13.0.0 (clang-1300.0.29.30)]
sys.executable: /Users/dorme/.pyenv/versions/3.10.4/bin/python3.10
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/Cellar/r/4.2.0/bin/Rscript', '--vanilla', '/var/folders/62/cz0ctby96lq7ggnytfbtd__40000gn/T/tmpgiuh095s/script.R')
return code: 1
stdout:
    * Querying repositories for available binary packages ... Done!
    Retrieving 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.cache_0.16.0.tgz' ...
    * Querying repositories for available source packages ... Done!
    Retrieving 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.cache_0.16.0.tar.gz' ...
    	OK [file is up to date]
    Retrieving 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.methodsS3_1.8.2.tgz' ...
    Retrieving 'https://packagemanager.rstudio.com/all/latest/src/contrib/Archive/R.cache/R.cache_0.16.0.tar.gz' ...
    	OK [file is up to date]
    Retrieving 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.oo_1.25.0.tgz' ...
stderr:
    # Bootstrapping renv 0.16.0 --------------------------------------------------
    * Downloading renv 0.16.0 ... OK
    * Installing renv 0.16.0 ... Done!
    * Successfully installed and loaded renv 0.16.0.
    The following package(s) will be updated:
    
    # CRAN ===============================
    - R.cache        [* -> 0.16.0]
    - R.methodsS3    [* -> 1.8.2]
    - R.oo           [* -> 1.25.0]
    - R6             [* -> 2.5.1]
    - Rcpp           [* -> 1.0.9]
    - backports      [* -> 1.4.1]
    - cyclocomp      [* -> 1.1.0]
    - desc           [* -> 1.4.2]
    - docopt         [* -> 0.7.1]
    - fs             [* -> 1.5.2]
    - git2r          [* -> 0.30.1]
    - glue           [* -> 1.6.2]
    - here           [* -> 1.0.1]
    - highr          [* -> 0.9]
    - hunspell       [* -> 3.0.2]
    - lazyeval       [* -> 0.2.2]
    - magrittr       [* -> 2.0.3]
    - remotes        [* -> 2.4.2]
    - rex            [* -> 1.2.1]
    - rprojroot      [* -> 2.0.3]
    - spelling       [* -> 2.2]
    - stringi        [* -> 1.7.8]
    - withr          [* -> 2.5.0]
    - xml2           [* -> 1.3.3]
    - xmlparsedata   [* -> 1.0.5]
    
    # GitHub =============================
    - styler         [* -> r-lib/styler@HEAD]
    
    # RSPM ===============================
    - R.utils        [* -> 2.12.2]
    - brew           [* -> 1.0-8]
    - callr          [* -> 3.7.3]
    - cli            [* -> 3.4.1]
    - commonmark     [* -> 1.8.1]
    - cpp11          [* -> 0.4.3]
    - crayon         [* -> 1.5.2]
    - digest         [* -> 0.6.31]
    - evaluate       [* -> 0.19]
    - jsonlite       [* -> 1.8.4]
    - knitr          [* -> 1.41]
    - lifecycle      [* -> 1.0.3]
    - lintr          [* -> 3.0.2]
    - pkgload        [* -> 1.3.2]
    - processx       [* -> 3.8.0]
    - ps             [* -> 1.7.2]
    - purrr          [* -> 0.3.5]
    - rlang          [* -> 1.0.6]
    - roxygen2       [* -> 7.2.3]
    - stringr        [* -> 1.5.0]
    - vctrs          [* -> 0.5.1]
    - xfun           [* -> 0.35]
    - yaml           [* -> 2.3.6]
    
    Warning: failed to retrieve 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.cache_0.16.0.tgz' [error code 22]
    Warning: failed to retrieve 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.methodsS3_1.8.2.tgz' [error code 22]
    Warning: failed to retrieve 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.oo_1.25.0.tgz' [error code 22]
    Error: failed to retrieve package 'R.cache@0.16.0'
    In addition: Warning messages:
    1: curl: (22) The requested URL returned error: 404 
    2: failed to retrieve 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.cache_0.16.0.tgz' [error code 22] 
    3: curl: (22) The requested URL returned error: 404 
    4: curl: (22) The requested URL returned error: 404 
    5: failed to retrieve 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.methodsS3_1.8.2.tgz' [error code 22] 
    6: curl: (22) The requested URL returned error: 404 
    Traceback (most recent calls last):
    8: renv::restore()
    7: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
    6: retrieve(packages)
    5: handler(package, renv_retrieve_impl(package))
    4: renv_retrieve_impl(package)
    3: renv_retrieve_repos(record)
    2: stopf("failed to retrieve package '%s'", renv_record_format_remote(record))
    1: stop(sprintf(fmt, ...), call. = call.)
    Execution halted
```

```
Traceback (most recent call last):
  File "/Users/dorme/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/Users/dorme/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pre_commit/main.py", line 396, in main
    return install(
  File "/Users/dorme/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pre_commit/commands/install_uninstall.py", line 140, in install
    install_hooks(config_file, store)
  File "/Users/dorme/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pre_commit/commands/install_uninstall.py", line 146, in install_hooks
    install_hook_envs(all_hooks(load_config(config_file), store), store)
  File "/Users/dorme/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "/Users/dorme/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pre_commit/repository.py", line 95, in _hook_install
    lang.install_environment(
  File "/Users/dorme/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pre_commit/languages/r.py", line 148, in install_environment
    cmd_output_b(_rscript_exec(), '--vanilla', f, cwd=env_dir)
  File "/Users/dorme/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/local/Cellar/r/4.2.0/bin/Rscript', '--vanilla', '/var/folders/62/cz0ctby96lq7ggnytfbtd__40000gn/T/tmpgiuh095s/script.R')
return code: 1
stdout:
    * Querying repositories for available binary packages ... Done!
    Retrieving 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.cache_0.16.0.tgz' ...
    * Querying repositories for available source packages ... Done!
    Retrieving 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.cache_0.16.0.tar.gz' ...
    	OK [file is up to date]
    Retrieving 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.methodsS3_1.8.2.tgz' ...
    Retrieving 'https://packagemanager.rstudio.com/all/latest/src/contrib/Archive/R.cache/R.cache_0.16.0.tar.gz' ...
    	OK [file is up to date]
    Retrieving 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.oo_1.25.0.tgz' ...
stderr:
    # Bootstrapping renv 0.16.0 --------------------------------------------------
    * Downloading renv 0.16.0 ... OK
    * Installing renv 0.16.0 ... Done!
    * Successfully installed and loaded renv 0.16.0.
    The following package(s) will be updated:
    
    # CRAN ===============================
    - R.cache        [* -> 0.16.0]
    - R.methodsS3    [* -> 1.8.2]
    - R.oo           [* -> 1.25.0]
    - R6             [* -> 2.5.1]
    - Rcpp           [* -> 1.0.9]
    - backports      [* -> 1.4.1]
    - cyclocomp      [* -> 1.1.0]
    - desc           [* -> 1.4.2]
    - docopt         [* -> 0.7.1]
    - fs             [* -> 1.5.2]
    - git2r          [* -> 0.30.1]
    - glue           [* -> 1.6.2]
    - here           [* -> 1.0.1]
    - highr          [* -> 0.9]
    - hunspell       [* -> 3.0.2]
    - lazyeval       [* -> 0.2.2]
    - magrittr       [* -> 2.0.3]
    - remotes        [* -> 2.4.2]
    - rex            [* -> 1.2.1]
    - rprojroot      [* -> 2.0.3]
    - spelling       [* -> 2.2]
    - stringi        [* -> 1.7.8]
    - withr          [* -> 2.5.0]
    - xml2           [* -> 1.3.3]
    - xmlparsedata   [* -> 1.0.5]
    
    # GitHub =============================
    - styler         [* -> r-lib/styler@HEAD]
    
    # RSPM ===============================
    - R.utils        [* -> 2.12.2]
    - brew           [* -> 1.0-8]
    - callr          [* -> 3.7.3]
    - cli            [* -> 3.4.1]
    - commonmark     [* -> 1.8.1]
    - cpp11          [* -> 0.4.3]
    - crayon         [* -> 1.5.2]
    - digest         [* -> 0.6.31]
    - evaluate       [* -> 0.19]
    - jsonlite       [* -> 1.8.4]
    - knitr          [* -> 1.41]
    - lifecycle      [* -> 1.0.3]
    - lintr          [* -> 3.0.2]
    - pkgload        [* -> 1.3.2]
    - processx       [* -> 3.8.0]
    - ps             [* -> 1.7.2]
    - purrr          [* -> 0.3.5]
    - rlang          [* -> 1.0.6]
    - roxygen2       [* -> 7.2.3]
    - stringr        [* -> 1.5.0]
    - vctrs          [* -> 0.5.1]
    - xfun           [* -> 0.35]
    - yaml           [* -> 2.3.6]
    
    Warning: failed to retrieve 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.cache_0.16.0.tgz' [error code 22]
    Warning: failed to retrieve 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.methodsS3_1.8.2.tgz' [error code 22]
    Warning: failed to retrieve 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.oo_1.25.0.tgz' [error code 22]
    Error: failed to retrieve package 'R.cache@0.16.0'
    In addition: Warning messages:
    1: curl: (22) The requested URL returned error: 404 
    2: failed to retrieve 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.cache_0.16.0.tgz' [error code 22] 
    3: curl: (22) The requested URL returned error: 404 
    4: curl: (22) The requested URL returned error: 404 
    5: failed to retrieve 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.methodsS3_1.8.2.tgz' [error code 22] 
    6: curl: (22) The requested URL returned error: 404 
    Traceback (most recent calls last):
    8: renv::restore()
    7: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
    6: retrieve(packages)
    5: handler(package, renv_retrieve_impl(package))
    4: renv_retrieve_impl(package)
    3: renv_retrieve_repos(record)
    2: stopf("failed to retrieve package '%s'", renv_record_format_remote(record))
    1: stop(sprintf(fmt, ...), call. = call.)
    Execution halted
```
</details>

**Comment by lorenzwalthert** [comment]
Creator of {precommit} here. There were some problems with binary packages in RSPM. Can you try to autoupdate the hooks `precommit::autoupdate()` and try again?

**Comment by davidorme** [comment]
@lorenzwalthert Many thanks for looking at this. I've autoupdated and `pre-commit` is now working.
